spring.application.name=projeto-expert
spring.profiles.active=test
cors.origins={192.168.15.188}
spring.jpa.open-in-view=false
security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}
security.jwt.duration=${JWT_DURATION:86400}